### ISSUE TITLE
Perl version

### ISSUE THREAD

**Issue by fridobox** [LMSCloud/LMSEventManagement#1]
https://github.com/LMSCloud/LMSEventManagement/blob/0ff1b9b836e543a5b8e4a05052c3a168c4b3b400/Koha/Plugin/Com/LMSCloud/EventManagement.pm#L6

Perl 5.32 is asked.
But I use Ubuntu Focal which as 5.30
https://packages.ubuntu.com/focal-updates/perl

Could it be compatible ?

**Comment by LMSCloudPaulD** [comment]
Hi Frido, just noticed your issue (need to fix email).
I just checked the codebase and I think it should run fine.

**Comment by fridobox** [comment]
OK so may you change in plugin to use 5.030 ?

**Comment by LMSCloudPaulD** [comment]
Hmm, honestly I don't want to, as it has already reached [EOL](https://endoflife.date/perl). But I just added a script to build the kpz files for 5.030 as well and will add them to the releases. If you need to rebuild you can use `npm run build:5.030`. If you just need the kpz right now use the \*-5.030-\*.kpz from the releases section.

Hope this approach works for you, Frido! Let me know whether you encounter any problems.

**Comment by fridobox** [comment]
No problem, I can also fork this repo.
Best regards ;)
